<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::create([
            'name' => 'Ei Kyaw',
            'uuid' => Str::uuid(),
            'email' => 'eikyaw@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'CST',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8921',
            'current_father_name' => 'U Kyaw Kyaw',
            'current_mother_name' => 'Daw Mya Mya',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123456789',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '1CST-2',
            'current_academic_year_id' => 1,
        ]);

        User::create([
            'name' => 'Ko khant',
            'uuid' => Str::uuid(),
            'email' => 'kokhant@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'CST',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8920',
            'current_father_name' => 'U Kyaw Moe',
            'current_mother_name' => 'Daw Mya Lin',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123456782',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '1CST-5',
            'current_academic_year_id' => 1,
        ]);

        User::create([
            'name' => 'Thin Wai',
            'uuid' => Str::uuid(),
            'email' => 'thinwai@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'CST',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8923',
            'current_father_name' => 'U Zaw Lin',
            'current_mother_name' => 'Daw Soe Soe',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123236789',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '1CST-3',
            'current_academic_year_id' => 2,
        ]);

        User::create([
            'name' => 'Thin Zar',
            'uuid' => Str::uuid(),
            'email' => 'thinzar@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'CST',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8922',
            'current_father_name' => 'U Zaw Aung',
            'current_mother_name' => 'Daw Soe Htet',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123236789',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '1CST-4',
            'current_academic_year_id' => 2,
        ]);

        User::create([
            'name' => 'Wai Yan',
            'uuid' => Str::uuid(),
            'email' => 'waiyan@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8925',
            'current_father_name' => 'U Thu Tun',
            'current_mother_name' => 'Daw Khin Khin',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123236789',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '2CS-5',
            'current_academic_year_id' => 3,
        ]);

        User::create([
            'name' => 'Ingyi',
            'uuid' => Str::uuid(),
            'email' => 'ingyi@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8924',
            'current_father_name' => 'U Min Min',
            'current_mother_name' => 'Daw Khin Mya',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123223789',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '2CS-32',
            'current_academic_year_id' => 3,
        ]);

        User::create([
            'name' => 'Moe Myint',
            'uuid' => Str::uuid(),
            'email' => 'moemyint@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer technology',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8927',
            'current_father_name' => 'U Phyo Min',
            'current_mother_name' => 'Daw Ngae Mya',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123223329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '2CT-22',
            'current_academic_year_id' => 4,
        ]);

        User::create([
            'name' => 'Myint Myat',
            'uuid' => Str::uuid(),
            'email' => 'myintmyat@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8926',
            'current_father_name' => 'U Phyo Min',
            'current_mother_name' => 'Daw Ngae Mya',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123783329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '2CS-11',
            'current_academic_year_id' => 4,
        ]);

        User::create([
            'name' => 'Ei Thwal',
            'uuid' => Str::uuid(),
            'email' => 'eithwal@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8928',
            'current_father_name' => 'U Khin Zaw',
            'current_mother_name' => 'Daw Mi Mi',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '3CS-5',
            'current_academic_year_id' => 5,
        ]);

        User::create([
            'name' => 'Si Si',
            'uuid' => Str::uuid(),
            'email' => 'sisi@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer technology',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8904',
            'current_father_name' => 'U Khin Kyi',
            'current_mother_name' => 'Daw May Mi',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '3CT-8',
            'current_academic_year_id' => 5,
        ]);

        User::create([
            'name' => 'Thet Phyoe',
            'uuid' => Str::uuid(),
            'email' => 'thetphyoe@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8931',
            'current_father_name' => 'U Tin Yee',
            'current_mother_name' => 'Daw May Mi',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '3CS-21',
            'current_academic_year_id' => 6,
        ]);

        User::create([
            'name' => 'Aung Bhone',
            'uuid' => Str::uuid(),
            'email' => 'aungbhone@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8930',
            'current_father_name' => 'U Tin Myint',
            'current_mother_name' => 'Daw Htar Yee',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '3CS-14',
            'current_academic_year_id' => 6,
        ]);

        User::create([
            'name' => 'Htoo Aung',
            'uuid' => Str::uuid(),
            'email' => 'htooaung@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer technology',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8933',
            'current_father_name' => 'U Myint Naing',
            'current_mother_name' => 'Daw Yee Yee',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '4CT-1',
            'current_academic_year_id' => 7,
        ]);

        User::create([
            'name' => 'Yati',
            'uuid' => Str::uuid(),
            'email' => 'yati@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8932',
            'current_father_name' => 'U Naing Naing',
            'current_mother_name' => 'Daw Su Su',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '4CS-4',
            'current_academic_year_id' => 7,
        ]);

        User::create([
            'name' => 'Aung Zae',
            'uuid' => Str::uuid(),
            'email' => 'aungzae@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8534',
            'current_father_name' => 'U Khin Oo',
            'current_mother_name' => 'Daw Su Myat',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '4CS-9',
            'current_academic_year_id' => 8,
        ]);

        User::create([
            'name' => 'Nway Oo',
            'uuid' => Str::uuid(),
            'email' => 'nwayoo@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer technology',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8935',
            'current_father_name' => 'U Maung Oo',
            'current_mother_name' => 'Daw Myat Myat',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '4CT-32',
            'current_academic_year_id' => 8,
        ]);

        User::create([
            'name' => 'Yaung Ni',
            'uuid' => Str::uuid(),
            'email' => 'yaungni@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer science',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8882',
            'current_father_name' => 'U Maung Maung',
            'current_mother_name' => 'Daw Myat Hnin',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '5CS-1',
            'current_academic_year_id' => 9,
        ]);

        User::create([
            'name' => 'Zar Zar',
            'uuid' => Str::uuid(),
            'email' => 'zarzar@ucsh.edu.mm',
            'role' => 'user',
            'major' => 'computer technology',
            'password' => 'P@ssw0rd',
            'image' => 'logo.jpg',
            'uni_Id_no' => 'CU(Hinthada)8919',
            'current_father_name' => 'U Naung Naung',
            'current_mother_name' => 'Daw Hnin Hnin',
            'current_NRC' => '12/ABK(N)123456',
            'DOB' => '2000-01-01',
            'permanent_address' => 'Hinthada, Myanmar',
            'phone' => '09123723329',
            'current_academic_year' => '2024-2025',
            'current_roll_number' => '5CT-1',
            'current_academic_year_id' => 9,
        ]);
    }
}
